const fs = require("fs");
const HtmlWebpackPlugin = require("html-webpack-plugin");

// Includes
const head = fs.readFileSync("src/includes/head.html");
const sectionHeader = fs.readFileSync("src/includes/section-header.html");
const sectionFooter = fs.readFileSync("src/includes/section-footer.html");
const temp = fs.readFileSync("src/includes/temp.html");

// Pages
module.exports = [
  new HtmlWebpackPlugin({
    template: "./src/index.html",
    filename: "index.html",
    inject: "body",
    title: "Med expert | Сеть семейных клиник",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/services.html",
    filename: "services.html",
    inject: "body",
    title: "Med expert | Услуги",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/services-detail.html",
    filename: "services-detail.html",
    inject: "body",
    title: "Med expert | Нефрология",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/about.html",
    filename: "about.html",
    inject: "body",
    title: "Med expert | О компании",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/about-vacancy.html",
    filename: "about-vacancy.html",
    inject: "body",
    title: "Med expert | Вакансии",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/about-history.html",
    filename: "about-history.html",
    inject: "body",
    title: "Med expert | История",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/about-mission.html",
    filename: "about-mission.html",
    inject: "body",
    title: "Med expert | Миссия компании",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/about-advisors.html",
    filename: "about-advisors.html",
    inject: "body",
    title: "Med expert | Руководство",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/about-license.html",
    filename: "about-license.html",
    inject: "body",
    title: "Med expert | Лицензии",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/sales.html",
    filename: "sales.html",
    inject: "body",
    title: "Med expert | Акции и скидки",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/for-kids.html",
    filename: "for-kids.html",
    inject: "body",
    title: "Med expert | Программы для детей",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/med-programs.html",
    filename: "med-programs.html",
    inject: "body",
    title: "Med expert | Медицинские программы",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/rehab.html",
    filename: "rehab.html",
    inject: "body",
    title: "Med expert | Восстановление",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/first-aid.html",
    filename: "first-aid.html",
    inject: "body",
    title: "Med expert | Первая помощь",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/ambulance.html",
    filename: "ambulance.html",
    inject: "body",
    title: "Med expert | Скорая помощь",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/price-by-options.html",
    filename: "price-by-options.html",
    inject: "body",
    title: "Med expert | Цены по направлениям",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/curing.html",
    filename: "curing.html",
    inject: "body",
    title: "Med expert | Лечение",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/curing-child.html",
    filename: "curing-child.html",
    inject: "body",
    title: "Med expert | Лечение детей",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/labtest.html",
    filename: "labtest.html",
    inject: "body",
    title: "Med expert | Лабораторные исследования",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/catalog.html",
    filename: "catalog.html",
    inject: "body",
    title: "Med expert | Каталог",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/catalog-detail.html",
    filename: "catalog-detail.html",
    inject: "body",
    title: "Med expert | Обследование щитовидной железы",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/vaccination.html",
    filename: "vaccination.html",
    inject: "body",
    title: "Med expert | Вакцинация",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/docs.html",
    filename: "docs.html",
    inject: "body",
    title: "Med expert | Врачи",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/docs-detail.html",
    filename: "docs-detail.html",
    inject: "body",
    title: "Med expert | Карточка специалиста",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/clinics.html",
    filename: "clinics.html",
    inject: "body",
    title: "Med expert | Клиники",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/clinics-detail.html",
    filename: "clinics-detail.html",
    inject: "body",
    title: "Med expert | Карточка центра",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/patients.html",
    filename: "patients.html",
    inject: "body",
    title: "Med expert | Пациентам",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/reviews.html",
    filename: "reviews.html",
    inject: "body",
    title: "Med expert | Отзывы",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/faq.html",
    filename: "faq.html",
    inject: "body",
    title: "Med expert | Вопросы и ответы",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/data.html",
    filename: "data.html",
    inject: "body",
    title: "Med expert | Обработка данных",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/dms.html",
    filename: "dms.html",
    inject: "body",
    title: "Med expert | ДМС",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/programs.html",
    filename: "programs.html",
    inject: "body",
    title: "Med expert | Программы обслуживания",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/news.html",
    filename: "news.html",
    inject: "body",
    title: "Med expert | Новости",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/news-detail.html",
    filename: "news-detail.html",
    inject: "body",
    title: "Med expert | Новости деталка",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/patients-info.html",
    filename: "patients-info.html",
    inject: "body",
    title: "Med expert | Информация для пациентов",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/rules-clinic.html",
    filename: "rules-clinic.html",
    inject: "body",
    title: "Med expert | Правила посещения клиники",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/rules-hosp.html",
    filename: "rules-hosp.html",
    inject: "body",
    title: "Med expert | Правила посещения стационара",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/payment.html",
    filename: "payment.html",
    inject: "body",
    title: "Med expert | Правила оплаты",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/search.html",
    filename: "search.html",
    inject: "body",
    title: "Med expert | Поиск",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/tax.html",
    filename: "tax.html",
    inject: "body",
    title: "Med expert | Налоговый вычет",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/cabinet.html",
    filename: "cabinet.html",
    inject: "body",
    title: "Med expert | Личный кабинет",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/ecosystem.html",
    filename: "ecosystem.html",
    inject: "body",
    title: "Med expert | Экосистема для клиентов",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
  new HtmlWebpackPlugin({
    template: "./src/pages/404.html",
    filename: "404.html",
    inject: "body",
    title: "Med expert | 404",
    head,
    sectionHeader,
    sectionFooter,
    temp,
  }),
];
